### PR TITLE
Possible approach for the TLS server.

### PR DESCRIPTION
**Pull request by gustavowd**

### CODE REVIEW

**Comment by uklotzde** [comment]
Why did you close the previous PR with my comments and instead reopened a new one???

**Comment by gustavowd** [comment]
> Why did you close the previous PR with my comments and instead reopened a new one???

Sorry.  It wasn't intentional.  I've never done a rebase before.  When I tried to resolve the conflict the pull request disappeared.

**Comment by uklotzde** [comment]
Pull requests can only be 

> > Why did you close the previous PR with my comments and instead reopened a new one???
> 
> Sorry. It wasn't intentional. I've never done a rebase before. When I tried to resolve the conflict the pull request disappeared.

Pull requests are only closed implicitly if you delete the underlying branch. Rebasing the branch locally and then force pushing should work as expected.

**Review by uklotzde — APPROVED** [review]
Thank you.

The client-side unwraps are ok for such a simple example. That's a different case than for the server-side which explicitly offers returning `Result`s in the framework code. The appropriate usage of those closure signatures should be demonstrated by an example.

**Pull request merged**
