### PR TITLE
Upgrade to tokio 1.0.

### LINKED ISSUE #71: Upgrade to tokio 0.3
Hi!

Currently tokio is on version 0.3.6, while this crate only supports the 0.2 versions of tokio.

Using the 0.3 versions of tokio leads to a `thread 'tokio-runtime-worker' panicked at 'there is no reactor running, must be called from the context of Tokio runtime'` runtime error, when using the tcp client to connect to something.

### PR DESCRIPTION
**Pull request by ivomurrell**
Now that tokio 1.0 is finally out, it seems like a good time to upgrade to the stable version so that other projects can use tokio-modbus after upgrading to tokio 1.0. Currently using the tokio 1.0 update for tokio-serial that is still in PR form so will have to treat this as a draft until that is merged and published. Nevertheless, seems like a fairly straightforward migration!

Closes #71

### CODE REVIEW

**Comment by OrangeTux** [comment]
Thanks for updating to Tokio 1.0!

**Comment by david-mcgillicuddy-moixa** [comment]
Once this is merged I have patch somewhat ready that re-adds RTU server support too: https://github.com/david-mcgillicuddy-moixa/tokio-modbus/commit/7004e39beab4bab97c415e119d2a582a0bb3e228
Happy enough just sitting on my fork for now, don't really feel like opening a PR on a PR!

**Comment by david-mcgillicuddy-moixa** [comment]
Just as an update on this, Ivo no longer works for Moixa so unless he feels extremely generous I'm happy to take this over. Having said that, tokio-serial's tokio-1.0 PR is still not merged due to the lack of windows support (also what is making the appveyor CI fail) so I don't see that any new progress can be made at the moment.

**Comment by ivomurrell** [comment]
My commitment to OSS extends beyond whoever my employer is! But it's true I no longer have the modbus equipment to test these changes so I'll take a bit more of a backseat... As @david-mcgillicuddy-moixa said, this is blocked on https://github.com/berkowski/tokio-serial/pull/33 so this should remain a draft for now.

**Comment by flosse** [comment]
Thanks @ivomurrell & @david-mcgillicuddy-moixa for your updates! :+1:

**Comment by ColinFinck** [comment]
Superseded by #76 ?

**Comment by david-mcgillicuddy-moixa** [comment]
There's a few differences, for example this PR doesn't have the multi-thread feature enabled and includes an RTU server too but largely they are trying to do the same thing. If the other PR included an RTU server then it'd work for us. I don't personally care about forcing the multi-threaded executor but if it's not actually necessary (i.e. if it was related to https://github.com/berkowski/tokio-serial/pull/33#discussion_r576928864 ) then it seems worth removing this.

Either way sure I'm happy to close this one.

**Comment by flosse** [comment]
closing in favor of #78

**Pull request closed without merging**
