### PR TITLE
Fixed WriteSingleCoil reponse to include data

### PR DESCRIPTION
**Pull request by thosaa**
Fixed issue #44 Reponse to WriteSingleCoil is malformed

### CODE REVIEW

**Comment by flosse** [comment]
Thanks for your PR!

At the moment it's failing because of this test: https://github.com/slowtec/tokio-modbus/blob/f9ff1b24f62fa04454d81502fcdd9612a089677e/src/codec/mod.rs#L609

**Comment by flosse** [comment]
fixed test in #46

**Comment by flosse** [comment]
... now I see you also fixed it ;-)

**Comment by thosaa** [comment]
Wow... I so slow... I was looking for a way to update the pull request. :-)

**Pull request closed without merging**
