### PR TITLE
New client/server API

### PR DESCRIPTION
**Pull request by uklotzde**
Some technical changes for the next evolution of the API:

- New `prelude` module that includes all public exports
- Isolate features in submodules
  - `rtu` / `tcp`
  - `sync`
- Split `ModbusClient` trait into `Client` + `Reader` + `Writer` traits
- Rename `Client` into `Connection`
   - synchronous / asynchronous
- Provide various `connect()` functions in submodules for establishing client connections
   - TCP / RTU
   - synchronous / asynchronous
- Move TCP server into submodule
- Client: Switch between different slaves dynamically at runtime

Migration instructions can be found in CHANGELOG.md and the examples reflect what users of this crate might need to change.

Maybe we should declare the server-side as _experimental_? Currently users are not able to control the TCP server instance once it has been attached to a port. This will hopefully change when we replace _tokio-core_ and _tokio-proto_.

### CODE REVIEW

**Comment by uklotzde** [comment]
Rebased on master for Rust 2018

**Comment by uklotzde** [comment]
@flosse I consider this ready for integration. As a next step I propose to migrate some dependent projects to the new API. If this works out as expected we may publish version 0.3.0.

Last-minute fix: The RTU decoder is now able to recover from frame errors instead of getting stuck with a broken pipe.

**Comment by uklotzde** [comment]
Please note that this PR subsumes #17

**Comment by uklotzde** [comment]
Ready for merging and creating a `v0.3` release branch for broader testing.

**Comment by axelfaure** [comment]
Thank you for the work you put in this new version!

I may have missed something but I think sync::Context should implement SlaveContext as well

**Comment by uklotzde** [comment]
Of course, thanks for the hint! Done.

**Comment by flosse** [comment]
@zzeroo Did you tried to use the new v0.3.x branch?

**Comment by axelfaure** [comment]
For the record, I have been successfully running a client using the new API in a testing environment (but against a real server) for almost 2 weeks now. 

It has been compared to a python script, the data retrieved is similar.
No unexpected behavior has been found. Slave id seems to be correctly taken into account.

I have not tested the server part, nor did I test the async version of the client (but I think the sync client is based on the async one)

**Comment by zzeroo** [comment]
@flosse how can I reach the v0.3.x branch? I think you mean `uklotzde:new_api`

Sorry for the delay, I hope I've some time now to test this crate. I'm willing to switch over from my libmodbus to this one ><

**Comment by flosse** [comment]
@axelfaure Thanks for your feedback!!

**Comment by flosse** [comment]
> @flosse how can I reach the v0.3.x branch? I think you mean `uklotzde:new_api`

exactly, I'm sorry for that confusion!

> Sorry for the delay, I hope I've some time now to test this crate. I'm willing to switch over from my libmodbus to this one ><

:+1:

We'll notify you as soon we published a stable `v0.3.x` release :)

**Comment by flosse** [comment]
@uklotzde I think we can merge this PR and make a release within the next few weeks :)

**Pull request merged**
