### PR TITLE
Allow for injection of TcpStream

### PR DESCRIPTION
**Pull request by fauve-edf**
## What
Allows for creating a `Context` with a custom tokio `TcpStream`. 

## Why
I want to be able to configure the socket. For example, you could set connect, read, and write timeouts. Really you could go hog wild and do whatever you want.

### CODE REVIEW

**Comment by uklotzde** [comment]
The last pre-commit failures are unrelated. Please rebase on #217 or wait until this PR has been merged.

**Comment by dr-kernel** [comment]
I would like to see this as well, I'm having issues where a write doesn't timeout forever.

**Comment by uklotzde** [comment]
Ping.

**Comment by fauve-edf** [comment]
Just to make sure, this functionality isn't just replicating https://docs.rs/tokio-modbus/latest/tokio_modbus/client/tcp/fn.attach.html ?

**Comment by uklotzde** [comment]
> Just to make sure, this functionality isn't just replicating https://docs.rs/tokio-modbus/latest/tokio_modbus/client/tcp/fn.attach.html ?

Indeed. Looks like this PR is obsolete.

**Pull request closed without merging**
