### PR TITLE
Remove `sync` from default features

### PR DESCRIPTION
**Pull request by uklotzde**
Please see the README for a yet unresolved side-effect. I didn't find a workaround for this limitation.

### CODE REVIEW

**Comment by uklotzde** [comment]
Force push after disabling the obsolete Travis and AppVeyor webhooks for the repo.

**Comment by bootrecords** [comment]
It should be able to work around the feature flag issues in doctests as well, [at least if I understand this correctly](https://stackoverflow.com/a/50314936) (I haven't tried it myself, though)

**Comment by uklotzde** [comment]
> It should be able to work around the feature flag issues in doctests as well, [at least if I understand this correctly](https://stackoverflow.com/a/50314936) (I haven't tried it myself, though)

We already use those attributes in lib.rs. But that doesn't prevent the doctests from being executed by `cargo test`.

**Review by flosse — APPROVED** [review]
LGTM

**Comment by flosse** [comment]
I also played around with some doctest / features tweaks but without success :(

**Pull request merged**
