### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by NateLing**

### CODE REVIEW

**Review by uklotzde — CHANGES_REQUESTED** [review]
I don't see any reason why we should increase the minor version number? Moreover a new version requires a changelog entry with the changes.

**Comment by uklotzde** [comment]
Please get familiar with the Git workflow. I recommend to use feature branches for development instead of committing changes directly on the `main` branch of your forked repo.

**Comment by NateLing** [comment]
@uklotzde sorry, i need to learn the Git workflow.

**Comment by uklotzde** [comment]
Closing due to no progress.

**Pull request closed without merging**
